baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "My New Hugo Site"

[outputFormats]
  [outputFormats.workflow]
    mediaType = "application/json"
    baseName = "workflow"
    notAlternative = true

[outputs]
  home = [ "HTML", "workflow"]

[taxonomies]
  tag = "tags"

[menu]

  [[menu.main]]
    identifier = "features"
    name = "Features"
    url = "/features/"
    weight = -130

  [[menu.main]]
    name = "Screenshots"
    url = "/screenshots/"
    weight = -120

  [[menu.main]]
    identifier = "workflows"
    name = "Workflows"
    url = "/workflows/"
    weight = -110

  [[menu.main]]
    identifier = "download"
    name = "Download"
    url = "/download/"
    weight = -100

  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = -90
